### ISSUE TITLE
Request: Publish the extension also in Open VSX

### ISSUE THREAD

**Issue by caio-vinicius** [dams333/CPP_Class_Generator#1]
https://open-vsx.org/

VSX is an open source repository of extensions for VSCode, which can be used by any version of VSCode today, not just products tied to Microsoft. It would be really cool if your beautiful extension was there ;)

**Comment by onora-hbl** [comment]
It's done! Thank you for the discovery, I did not know this platform
https://open-vsx.org/extension/DamienHubleur/cppclassgenerator
The request for the namespace to belong to me is in progress but normally the extension is available
Don't hesitate to tell me if everything works on your side so that I can close your issue

**Comment by caio-vinicius** [comment]
Thanks, I will test in the code-server https://github.com/coder/code-server installation that I'm been using recently and let you know about how it works.

Also, I just share your extension in my 42 community, here in 42 São Paulo. Thanks for the work, very nice. Hope more people in the 42 community find your extension. Already publish in the 42born2code Slack? Haha

**Comment by onora-hbl** [comment]
Only for 42 Paris for the moment, I was waiting to see if the interface works (not being a frontend developer I was afraid it would only work for me xD) but I'm going to test it on Monday on the computers at 42 Paris, and if you confirm that it works well too, I'll share it on the slack world
If you or other students from Sao Polo have any problems, please do not hesitate to make an issue or a PR ;)
